### ISSUE TITLE
Fix Github action lacking API Key

### ISSUE THREAD

**Issue by dwu0042** [numbats/airpurifyr#1]
We should use secrets in the Github action workflow to pass in an API Key:

[docs](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions)

Because we read in from the environment, we can just set it and the package should pick it up.

**Comment by MikeLydeamore** [comment]
Fix for this apparently is to pre-load the data required for the vignette, and not have that part of the code execute. We _could_ fix this by querying the API but that happening on every push seems not ideal to me.

Fixed in f8f3eff032a9349ed11ab924563e0bd3a0b56a79 (plus the missing suggests in 78f5d6558ff9df8d239eea284b9ef66167b61b6e)
